{"timestamp":"2025-10-05T09:18:08.480586Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-05T09:18:08.482030Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retail_transaction.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-05T09:18:08.503152Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/retail_transaction.py","lineno":4,"logger":"py.warnings"}
{"timestamp":"2025-10-05T09:18:08.524757Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.525863Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.526780Z","level":"info","event":"Current task name:ensure_tables_task","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.527715Z","level":"info","event":"Dag name:etl_retail_transactions_autocreate","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.537574Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.InvalidSchemaName) schema \"source\" does not exist\nLINE 2:             CREATE TABLE IF NOT EXISTS source.retail_transac...\n                                               ^\n\n[SQL: \n            CREATE TABLE IF NOT EXISTS source.retail_transactions (\n                id SERIAL PRIMARY KEY,\n                customer_id INT NOT NULL,\n                last_status VARCHAR(50),\n                pos_origin VARCHAR(50),\n                pos_destination VARCHAR(50),\n                created_at TIMESTAMP,\n                updated_at TIMESTAMP\n            )\n        ]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/retail_transaction.py","lineno":76,"name":"ensure_tables"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py","lineno":334,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1577,"name":"_execute_clauseelement"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"InvalidSchemaName","exc_value":"schema \"source\" does not exist\nLINE 2:             CREATE TABLE IF NOT EXISTS source.retail_transac...\n                                               ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-05T09:18:08.568882Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.570137Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.571071Z","level":"info","event":"Task:<Task(PythonOperator): ensure_tables_task>","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.571919Z","level":"info","event":"Failure caused by (psycopg2.errors.InvalidSchemaName) schema \"source\" does not exist","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.572891Z","level":"info","event":"LINE 2:             CREATE TABLE IF NOT EXISTS source.retail_transac...","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.573988Z","level":"info","event":"                                               ^","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.574948Z","level":"info","event":"","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.575849Z","level":"info","event":"[SQL:","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.577066Z","level":"info","event":"            CREATE TABLE IF NOT EXISTS source.retail_transactions (","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.578253Z","level":"info","event":"                id SERIAL PRIMARY KEY,","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.579584Z","level":"info","event":"                customer_id INT NOT NULL,","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.580710Z","level":"info","event":"                last_status VARCHAR(50),","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.581802Z","level":"info","event":"                pos_origin VARCHAR(50),","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.582970Z","level":"info","event":"                pos_destination VARCHAR(50),","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.584248Z","level":"info","event":"                created_at TIMESTAMP,","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.585421Z","level":"info","event":"                updated_at TIMESTAMP","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.586571Z","level":"info","event":"            )","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.587743Z","level":"info","event":"        ]","logger":"task.stdout"}
{"timestamp":"2025-10-05T09:18:08.588811Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"task.stdout"}
